{
    'name': "Tanda Terima Invoice",
    'version': '12.0.0.0.1',
    'summary': """Print Tanda Terima invoice""",
    'description': """Membuat Tanda Terima Invoice""",
    'category': 'Accounting',
    'author': 'Ahmad Heriyanto',
    'company': 'Nikisae',
    'maintainer': 'Ahmad Heriyanto',
    'website': "https://id.linkedin.com/in/ahmadheriyanto ",
    'depends': ['base', 'account'],
    'data': [
        "report/penerimaan_kas.xml",
        "report/pengeluaran_kas.xml",
    ],
    'images': [],
    'license': "AGPL-3",
    'installable': True,
    'application': False,
}
